//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    //using System.Data.Objects;
    //using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DB_ExamContext : DbContext
    {
        public DB_ExamContext()
            : base("name=DB_ExamContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_SYS_FILE_PATH_CONFIG> T_SYS_FILE_PATH_CONFIG { get; set; }
        public DbSet<T_AUTHORIZED_EXAM> T_AUTHORIZED_EXAM { get; set; }
        public DbSet<T_AUTHORIZED_READ_PAPERS_USER> T_AUTHORIZED_READ_PAPERS_USER { get; set; }
        public DbSet<T_CODE_TABLE> T_CODE_TABLE { get; set; }
        public DbSet<T_DEGREE> T_DEGREE { get; set; }
        public DbSet<T_DEPARTMENT> T_DEPARTMENT { get; set; }
        public DbSet<T_EXAM_PLAN> T_EXAM_PLAN { get; set; }
        public DbSet<T_EXAM_PLAN_ANSWER> T_EXAM_PLAN_ANSWER { get; set; }
        public DbSet<T_EXAM_TYPE> T_EXAM_TYPE { get; set; }
        public DbSet<T_KNOWLEDGE> T_KNOWLEDGE { get; set; }
        public DbSet<T_OP_REF_ROLE> T_OP_REF_ROLE { get; set; }
        public DbSet<T_OPERATION> T_OPERATION { get; set; }
        public DbSet<T_PAPER> T_PAPER { get; set; }
        public DbSet<T_PAPER_QUESTION_TYPE> T_PAPER_QUESTION_TYPE { get; set; }
        public DbSet<T_PAPERQUESTION_TYPE_QUESTION> T_PAPERQUESTION_TYPE_QUESTION { get; set; }
        public DbSet<T_PERFORMANCE_RULES> T_PERFORMANCE_RULES { get; set; }
        public DbSet<T_PERFORMANCE_RULES_ITEMS> T_PERFORMANCE_RULES_ITEMS { get; set; }
        public DbSet<T_POSITION> T_POSITION { get; set; }
        public DbSet<T_QUESTION> T_QUESTION { get; set; }
        public DbSet<T_QUESTION_TEMPLATE> T_QUESTION_TEMPLATE { get; set; }
        public DbSet<T_QUESTION_TYPE> T_QUESTION_TYPE { get; set; }
        public DbSet<T_QUESTION_TYPE_RF_KNOWLEDGE> T_QUESTION_TYPE_RF_KNOWLEDGE { get; set; }
        public DbSet<T_ROLE> T_ROLE { get; set; }
        public DbSet<T_SCORES> T_SCORES { get; set; }
        public DbSet<T_SYS_FILE_BODY> T_SYS_FILE_BODY { get; set; }
        public DbSet<T_SYS_FILE_INFO> T_SYS_FILE_INFO { get; set; }
        public DbSet<T_USER> T_USER { get; set; }
        public DbSet<V_AUTHOR_DEPARTMENT> V_AUTHOR_DEPARTMENT { get; set; }
        public DbSet<V_AUTHOR_POSITION> V_AUTHOR_POSITION { get; set; }
        public DbSet<V_AUTHOR_REVIWERS> V_AUTHOR_REVIWERS { get; set; }
        public DbSet<V_AUTHOR_USER> V_AUTHOR_USER { get; set; }
        public DbSet<V_EXAM_PLAN_INFO> V_EXAM_PLAN_INFO { get; set; }
        public DbSet<V_EXAM_QUESTION_TYPE> V_EXAM_QUESTION_TYPE { get; set; }
        public DbSet<V_PAPER_INFO> V_PAPER_INFO { get; set; }
        public DbSet<V_PAPER_QUESTION_INFO> V_PAPER_QUESTION_INFO { get; set; }
        public DbSet<V_PERFORMANCE_RULES_INFO> V_PERFORMANCE_RULES_INFO { get; set; }
        public DbSet<V_QUESTION_INFO> V_QUESTION_INFO { get; set; }
        public DbSet<V_TABLE_CODE_MAKE_WAY> V_TABLE_CODE_MAKE_WAY { get; set; }
        public DbSet<V_TABLE_CODE_PAPER_TYPE> V_TABLE_CODE_PAPER_TYPE { get; set; }
        public DbSet<V_USER_INFO> V_USER_INFO { get; set; }
        public DbSet<T_AppConfig> T_AppConfig { get; set; }
    
        public virtual ObjectResult<P_QUERY_MY_EXAMS_Result> P_QUERY_MY_EXAMS(string userid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_QUERY_MY_EXAMS_Result>("P_QUERY_MY_EXAMS", useridParameter);
        }
    }
}
