//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DEGREE
    {
        public T_DEGREE()
        {
            this.T_USER = new HashSet<T_USER>();
        }
    
        public System.Guid ID { get; set; }
        public string DEGREE_NAME { get; set; }
        public string DEGREE_DESC { get; set; }
        public string SEQUENCE { get; set; }
    
        public virtual ICollection<T_USER> T_USER { get; set; }
    }
}
