//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EXAM_TYPE
    {
        public T_EXAM_TYPE()
        {
            this.T_PAPER = new HashSet<T_PAPER>();
        }
    
        public System.Guid ID { get; set; }
        public string EXAM_TYPE_NAME { get; set; }
        public string EXAM_TYPE_DESC { get; set; }
        public Nullable<System.Guid> PARENT_ID { get; set; }
        public string SEQUENCE { get; set; }
    
        public virtual ICollection<T_PAPER> T_PAPER { get; set; }
    }
}
