//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EXAM_PLAN_ANSWER
    {
        public System.Guid USER_ID { get; set; }
        public System.Guid EXAM_ID { get; set; }
        public System.Guid QUESTIONS_ID { get; set; }
        public string USER_ANSWERS { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public Nullable<System.Guid> READ_PAPERS_USER { get; set; }
        public Nullable<System.DateTime> JUDGE_DATE { get; set; }
    
        public virtual T_EXAM_PLAN T_EXAM_PLAN { get; set; }
        public virtual T_QUESTION T_QUESTION { get; set; }
        public virtual T_USER T_USER { get; set; }
    }
}
