//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_KNOWLEDGE
    {
        public T_KNOWLEDGE()
        {
            this.T_QUESTION = new HashSet<T_QUESTION>();
            this.T_QUESTION_TYPE_RF_KNOWLEDGE = new HashSet<T_QUESTION_TYPE_RF_KNOWLEDGE>();
        }
    
        public System.Guid ID { get; set; }
        public string KNOWLEDGE_NAME { get; set; }
        public string KNOWLEDGE_DESC { get; set; }
        public Nullable<System.Guid> PARENT_ID { get; set; }
        public string SEQUENCE { get; set; }
        public Nullable<System.Guid> CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    
        public virtual ICollection<T_QUESTION> T_QUESTION { get; set; }
        public virtual ICollection<T_QUESTION_TYPE_RF_KNOWLEDGE> T_QUESTION_TYPE_RF_KNOWLEDGE { get; set; }
    }
}
