//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OPERATION
    {
        public T_OPERATION()
        {
            this.T_OP_REF_ROLE = new HashSet<T_OP_REF_ROLE>();
        }
    
        public System.Guid ID { get; set; }
        public string OP_NAME { get; set; }
        public string OP_CODE { get; set; }
        public string OP_DESC { get; set; }
        public string APPLICATION_FILE { get; set; }
        public Nullable<System.Guid> PARENT_OP_ID { get; set; }
        public string SEQUENCE { get; set; }
        public string ICON_PATH { get; set; }
        public string DISPLAYFLAG { get; set; }
    
        public virtual ICollection<T_OP_REF_ROLE> T_OP_REF_ROLE { get; set; }
    }
}
