//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PAPER_QUESTION_TYPE
    {
        public T_PAPER_QUESTION_TYPE()
        {
            this.T_PAPERQUESTION_TYPE_QUESTION = new HashSet<T_PAPERQUESTION_TYPE_QUESTION>();
            this.T_QUESTION_TYPE_RF_KNOWLEDGE = new HashSet<T_QUESTION_TYPE_RF_KNOWLEDGE>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> QUESTION_TYPE_ID { get; set; }
        public Nullable<System.Guid> EXAM_ID { get; set; }
        public string TITLE { get; set; }
        public string SUBTITLE { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public Nullable<int> LOW_DIFFICULTY_QUESTIONS_COUNT { get; set; }
        public Nullable<int> MEDIUM_DIFFICULTY_QUESTIONS_COUNT { get; set; }
        public Nullable<int> HIGH_DIFFICULTY_QUESTIONS_COUNT { get; set; }
        public string SEQUENCE { get; set; }
        public Nullable<System.Guid> CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string REMARK { get; set; }
    
        public virtual T_PAPER T_PAPER { get; set; }
        public virtual T_QUESTION_TYPE T_QUESTION_TYPE { get; set; }
        public virtual ICollection<T_PAPERQUESTION_TYPE_QUESTION> T_PAPERQUESTION_TYPE_QUESTION { get; set; }
        public virtual ICollection<T_QUESTION_TYPE_RF_KNOWLEDGE> T_QUESTION_TYPE_RF_KNOWLEDGE { get; set; }
    }
}
