//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PAPERQUESTION_TYPE_QUESTION
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> QUESTIONS_ID { get; set; }
        public Nullable<System.Guid> PAPER_QUESTION_TYPE_ID { get; set; }
        public string SEQUENCE { get; set; }
    
        public virtual T_PAPER_QUESTION_TYPE T_PAPER_QUESTION_TYPE { get; set; }
        public virtual T_QUESTION T_QUESTION { get; set; }
    }
}
