//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PAPER
    {
        public T_PAPER()
        {
            this.T_EXAM_PLAN = new HashSet<T_EXAM_PLAN>();
            this.T_PAPER_QUESTION_TYPE = new HashSet<T_PAPER_QUESTION_TYPE>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> EXAM_TYPE_ID { get; set; }
        public string PAPER_NAME { get; set; }
        public string PAPER_DESC { get; set; }
        public Nullable<System.Guid> MAKE_QUESTION_TYPE { get; set; }
        public Nullable<System.Guid> PAPER_TYPE { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.Guid> CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    
        public virtual ICollection<T_EXAM_PLAN> T_EXAM_PLAN { get; set; }
        public virtual T_EXAM_TYPE T_EXAM_TYPE { get; set; }
        public virtual ICollection<T_PAPER_QUESTION_TYPE> T_PAPER_QUESTION_TYPE { get; set; }
    }
}
