//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QUESTION
    {
        public T_QUESTION()
        {
            this.T_EXAM_PLAN_ANSWER = new HashSet<T_EXAM_PLAN_ANSWER>();
            this.T_PAPERQUESTION_TYPE_QUESTION = new HashSet<T_PAPERQUESTION_TYPE_QUESTION>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> QUESTION_TYPE_ID { get; set; }
        public Nullable<System.Guid> KNOWLEDGE_ID { get; set; }
        public string DIFFICULTY { get; set; }
        public string SHOW_IN_PRACTICE { get; set; }
        public string QUESTION_CONTENT { get; set; }
        public string QUESTION_OPTIONS { get; set; }
        public Nullable<int> QUESTION_OPTIONS_COUNT { get; set; }
        public string ANSWERS { get; set; }
        public string ANSWER_ANALYSIS { get; set; }
        public Nullable<System.Guid> CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    
        public virtual ICollection<T_EXAM_PLAN_ANSWER> T_EXAM_PLAN_ANSWER { get; set; }
        public virtual T_KNOWLEDGE T_KNOWLEDGE { get; set; }
        public virtual ICollection<T_PAPERQUESTION_TYPE_QUESTION> T_PAPERQUESTION_TYPE_QUESTION { get; set; }
        public virtual T_QUESTION_TYPE T_QUESTION_TYPE { get; set; }
    }
}
