//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QUESTION_TYPE
    {
        public T_QUESTION_TYPE()
        {
            this.T_PAPER_QUESTION_TYPE = new HashSet<T_PAPER_QUESTION_TYPE>();
            this.T_QUESTION = new HashSet<T_QUESTION>();
        }
    
        public System.Guid ID { get; set; }
        public string QUESTION_TYPE_NAME { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public Nullable<System.Guid> TEMPLATE_ID { get; set; }
        public string SEQUENCE { get; set; }
    
        public virtual ICollection<T_PAPER_QUESTION_TYPE> T_PAPER_QUESTION_TYPE { get; set; }
        public virtual ICollection<T_QUESTION> T_QUESTION { get; set; }
        public virtual T_QUESTION_TEMPLATE T_QUESTION_TEMPLATE { get; set; }
    }
}
