//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_FILE_BODY
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> SYS_FILE_INFO_ID { get; set; }
        public byte[] SYS_FILE_CONTENT { get; set; }
        public Nullable<decimal> FILE_SIZE { get; set; }
        public Nullable<System.Guid> UPLOAD_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public Nullable<System.Guid> UPDATE_USER_ID { get; set; }
    
        public virtual T_SYS_FILE_INFO T_SYS_FILE_INFO { get; set; }
    }
}
