//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SYS_FILE_PATH_CONFIG
    {
        public T_SYS_FILE_PATH_CONFIG()
        {
            this.T_SYS_FILE_INFO = new HashSet<T_SYS_FILE_INFO>();
        }
    
        public System.Guid ID { get; set; }
        public string FILE_TYPE { get; set; }
        public string FILE_PATH { get; set; }
        public string SERVER_FULL_PATH { get; set; }
    
        public virtual ICollection<T_SYS_FILE_INFO> T_SYS_FILE_INFO { get; set; }
    }
}
