//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER
    {
        public T_USER()
        {
            this.T_AUTHORIZED_READ_PAPERS_USER = new HashSet<T_AUTHORIZED_READ_PAPERS_USER>();
            this.T_EXAM_PLAN_ANSWER = new HashSet<T_EXAM_PLAN_ANSWER>();
            this.T_SCORES = new HashSet<T_SCORES>();
        }
    
        public System.Guid ID { get; set; }
        public string LOGIN_NAME { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<System.Guid> POSITION_ID { get; set; }
        public Nullable<System.Guid> ROLE_ID { get; set; }
        public Nullable<System.Guid> DEGREE_ID { get; set; }
        public string USER_PWD { get; set; }
        public string IDENTITY_CARD_CODE { get; set; }
        public string USER_TEL { get; set; }
        public string USER_MOBILE { get; set; }
        public string USER_CONTACT { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.Guid> USER_PHOTO { get; set; }
        public string POSTCODE { get; set; }
        public Nullable<System.Guid> CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string SEX { get; set; }
        public Nullable<System.Guid> DEPARTMENT_ID { get; set; }
        public Nullable<int> USER_STATUS { get; set; }
    
        public virtual ICollection<T_AUTHORIZED_READ_PAPERS_USER> T_AUTHORIZED_READ_PAPERS_USER { get; set; }
        public virtual T_DEGREE T_DEGREE { get; set; }
        public virtual T_DEPARTMENT T_DEPARTMENT { get; set; }
        public virtual ICollection<T_EXAM_PLAN_ANSWER> T_EXAM_PLAN_ANSWER { get; set; }
        public virtual T_POSITION T_POSITION { get; set; }
        public virtual T_ROLE T_ROLE { get; set; }
        public virtual ICollection<T_SCORES> T_SCORES { get; set; }
    }
}
