//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_EXAM_QUESTION_TYPE
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> EXAM_ID { get; set; }
        public string QUESTION_TYPE_NAME { get; set; }
        public string TITLE { get; set; }
        public string SEQUENCE { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public Nullable<int> LOW_DIFFICULTY_QUESTIONS_COUNT { get; set; }
        public Nullable<int> MEDIUM_DIFFICULTY_QUESTIONS_COUNT { get; set; }
        public Nullable<int> HIGH_DIFFICULTY_QUESTIONS_COUNT { get; set; }
    }
}
