//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_QUESTION_INFO
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> QUESTION_TYPE_ID { get; set; }
        public Nullable<System.Guid> KNOWLEDGE_ID { get; set; }
        public string DIFFICULTY { get; set; }
        public string SHOW_IN_PRACTICE { get; set; }
        public string QUESTION_CONTENT { get; set; }
        public string QUESTION_OPTIONS { get; set; }
        public Nullable<int> QUESTION_OPTIONS_COUNT { get; set; }
        public string ANSWERS { get; set; }
        public string ANSWER_ANALYSIS { get; set; }
        public Nullable<System.Guid> CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string KNOWLEDGE_NAME { get; set; }
        public string KNOWLEDGE_DESC { get; set; }
        public Nullable<System.Guid> PARENT_ID { get; set; }
        public string KNOWLEDGE_SEQUENCE { get; set; }
        public string QUESTION_TYPE_NAME { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public string QUESTION_TYPE_SEQUENCE { get; set; }
        public Nullable<System.Guid> TEMPLATE_ID { get; set; }
        public string TEMPLATE_NAME { get; set; }
        public string QUESTION_TEMPLATE_SEQUENCE { get; set; }
    }
}
