//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_USER_INFO
    {
        public System.Guid ID { get; set; }
        public string LOGIN_NAME { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<System.Guid> POSITION_ID { get; set; }
        public Nullable<System.Guid> ROLE_ID { get; set; }
        public Nullable<System.Guid> DEGREE_ID { get; set; }
        public string USER_PWD { get; set; }
        public string IDENTITY_CARD_CODE { get; set; }
        public string USER_TEL { get; set; }
        public string USER_MOBILE { get; set; }
        public string USER_CONTACT { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.Guid> USER_PHOTO { get; set; }
        public string POSTCODE { get; set; }
        public Nullable<System.Guid> CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string SEX { get; set; }
        public Nullable<System.Guid> DEPARTMENT_ID { get; set; }
        public Nullable<int> USER_STATUS { get; set; }
        public string POSITION_NAME { get; set; }
        public string DEGREE_NAME { get; set; }
        public string ROLE_NAME { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string SERVER_FULL_PATH { get; set; }
    }
}
