//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ELE_METER_CHARGE_RECORD
    {
        public string ID { get; set; }
        public string CARD_CODE { get; set; }
        public Nullable<double> CAHREG_VOLUME { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> CHARGE_FEE { get; set; }
        public string CHARGE_COUNT { get; set; }
        public Nullable<double> CHARGE_SUM { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
namespace IC.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ELE_METER_INFO
    {
        public System.Guid ID { get; set; }
        public string CARD_CODE { get; set; }
        public Nullable<int> COUNT { get; set; }
        public Nullable<double> CHARGE_SUM { get; set; }
        public Nullable<double> CHARGE_PREVIOUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string REMARK { get; set; }
    }
}
