//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class IC_TEST_Context : DbContext
    {
        public IC_TEST_Context()
            : base("name=IC_TEST_ConnString")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<T_ELE_METER_CHARGE_RECORD> T_ELE_METER_CHARGE_RECORD { get; set; }
        public DbSet<T_ELE_METER_INFO> T_ELE_METER_INFO { get; set; }
    }
}
