
namespace XCI.WinUtility.GridConfig
{
    partial class GridColumnEditor
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.editSearchBox = new XCI.WinUtility.XCIButtonEdit();
            this.btnAutoGenerated = new DevExpress.XtraEditors.SimpleButton();
            this.propertyGridGridColumn = new XCI.WinUtility.XCIPropertyGrid();
            this.comboxCaption = new DevExpress.XtraEditors.Repository.RepositoryItemComboBox();
            this.btnDelete = new DevExpress.XtraEditors.SimpleButton();
            this.gridGridColumn = new XCI.WinUtility.XCIGrid();
            this.gridViewGridColumn = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.comboxFieldName = new DevExpress.XtraEditors.Repository.RepositoryItemComboBox();
            this.btnNew = new DevExpress.XtraEditors.SimpleButton();
            this.splitContainerControl1 = new DevExpress.XtraEditors.SplitContainerControl();
            ((System.ComponentModel.ISupportInitialize)(this.editSearchBox.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.comboxCaption)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridGridColumn)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridViewGridColumn)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.comboxFieldName)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainerControl1)).BeginInit();
            this.splitContainerControl1.SuspendLayout();
            this.SuspendLayout();
            // 
            // editSearchBox
            // 
            this.editSearchBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.editSearchBox.EnableChangerBackColor = false;
            this.editSearchBox.EnableZeroConvertEmpty = false;
            this.editSearchBox.Location = new System.Drawing.Point(0, 3);
            this.editSearchBox.Name = "editSearchBox";
            this.editSearchBox.Size = new System.Drawing.Size(503, 20);
            this.editSearchBox.TabIndex = 23;
            this.editSearchBox.WaterMarkColor = System.Drawing.Color.Gray;
            this.editSearchBox.WaterMarkFont = null;
            this.editSearchBox.WaterMarkText = "请输入搜索关键字";
            this.editSearchBox.EditValueChanged += new System.EventHandler(this.editSearchBox_EditValueChanged);
            // 
            // btnAutoGenerated
            // 
            this.btnAutoGenerated.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAutoGenerated.Location = new System.Drawing.Point(722, 3);
            this.btnAutoGenerated.Name = "btnAutoGenerated";
            this.btnAutoGenerated.Size = new System.Drawing.Size(121, 30);
            this.btnAutoGenerated.TabIndex = 20;
            this.btnAutoGenerated.Text = "自动生成列";
            this.btnAutoGenerated.Click += new System.EventHandler(this.btnAutoGenerated_Click);
            // 
            // propertyGridGridColumn
            // 
            this.propertyGridGridColumn.Appearance.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.propertyGridGridColumn.Appearance.Options.UseFont = true;
            this.propertyGridGridColumn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.propertyGridGridColumn.Location = new System.Drawing.Point(0, 0);
            this.propertyGridGridColumn.Margin = new System.Windows.Forms.Padding(4);
            this.propertyGridGridColumn.Name = "propertyGridGridColumn";
            this.propertyGridGridColumn.Size = new System.Drawing.Size(387, 460);
            this.propertyGridGridColumn.TabIndex = 22;
            // 
            // comboxCaption
            // 
            this.comboxCaption.AutoHeight = false;
            this.comboxCaption.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.comboxCaption.Name = "comboxCaption";
            // 
            // btnDelete
            // 
            this.btnDelete.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnDelete.Location = new System.Drawing.Point(616, 3);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.Size = new System.Drawing.Size(100, 30);
            this.btnDelete.TabIndex = 18;
            this.btnDelete.Text = "删除...";
            this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
            // 
            // gridGridColumn
            // 
            this.gridGridColumn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridGridColumn.GridID = "324cba5c279e49eda8889b5abdfa4dc4";
            this.gridGridColumn.IsShowColumnHeardMenu = true;
            this.gridGridColumn.Location = new System.Drawing.Point(0, 0);
            this.gridGridColumn.MainView = this.gridViewGridColumn;
            this.gridGridColumn.Name = "gridGridColumn";
            this.gridGridColumn.RepositoryItems.AddRange(new DevExpress.XtraEditors.Repository.RepositoryItem[] {
            this.comboxFieldName,
            this.comboxCaption});
            this.gridGridColumn.Size = new System.Drawing.Size(508, 460);
            this.gridGridColumn.TabIndex = 21;
            this.gridGridColumn.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.gridViewGridColumn});
            // 
            // gridViewGridColumn
            // 
            this.gridViewGridColumn.GridControl = this.gridGridColumn;
            this.gridViewGridColumn.Name = "gridViewGridColumn";
            this.gridViewGridColumn.OptionsView.ShowDetailButtons = false;
            this.gridViewGridColumn.FocusedRowChanged += new DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventHandler(this.gridViewGridColumn_FocusedRowChanged);
            // 
            // comboxFieldName
            // 
            this.comboxFieldName.AutoHeight = false;
            this.comboxFieldName.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.comboxFieldName.Name = "comboxFieldName";
            // 
            // btnNew
            // 
            this.btnNew.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnNew.Location = new System.Drawing.Point(510, 3);
            this.btnNew.Name = "btnNew";
            this.btnNew.Size = new System.Drawing.Size(100, 30);
            this.btnNew.TabIndex = 19;
            this.btnNew.Text = "新建...";
            this.btnNew.Click += new System.EventHandler(this.btnNew_Click);
            // 
            // splitContainerControl1
            // 
            this.splitContainerControl1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.splitContainerControl1.FixedPanel = DevExpress.XtraEditors.SplitFixedPanel.Panel2;
            this.splitContainerControl1.Location = new System.Drawing.Point(0, 40);
            this.splitContainerControl1.Name = "splitContainerControl1";
            this.splitContainerControl1.Panel1.Controls.Add(this.gridGridColumn);
            this.splitContainerControl1.Panel1.Text = "Panel1";
            this.splitContainerControl1.Panel2.Controls.Add(this.propertyGridGridColumn);
            this.splitContainerControl1.Panel2.Text = "Panel2";
            this.splitContainerControl1.Size = new System.Drawing.Size(900, 460);
            this.splitContainerControl1.SplitterPosition = 387;
            this.splitContainerControl1.TabIndex = 24;
            this.splitContainerControl1.Text = "splitContainerControl1";
            // 
            // GridColumnEditor
            // 
            this.Appearance.Font = new System.Drawing.Font("微软雅黑", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Appearance.Options.UseFont = true;
            this.AutoScaleDimensions = new System.Drawing.SizeF(10F, 21F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.splitContainerControl1);
            this.Controls.Add(this.editSearchBox);
            this.Controls.Add(this.btnAutoGenerated);
            this.Controls.Add(this.btnDelete);
            this.Controls.Add(this.btnNew);
            this.Name = "GridColumnEditor";
            this.Size = new System.Drawing.Size(900, 500);
            ((System.ComponentModel.ISupportInitialize)(this.editSearchBox.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.comboxCaption)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridGridColumn)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridViewGridColumn)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.comboxFieldName)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainerControl1)).EndInit();
            this.splitContainerControl1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private WinUtility.XCIButtonEdit editSearchBox;
        private DevExpress.XtraEditors.SimpleButton btnAutoGenerated;
        private WinUtility.XCIPropertyGrid propertyGridGridColumn;
        private DevExpress.XtraEditors.Repository.RepositoryItemComboBox comboxCaption;
        private DevExpress.XtraEditors.SimpleButton btnDelete;
        private WinUtility.XCIGrid gridGridColumn;
        private DevExpress.XtraGrid.Views.Grid.GridView gridViewGridColumn;
        private DevExpress.XtraEditors.Repository.RepositoryItemComboBox comboxFieldName;
        private DevExpress.XtraEditors.SimpleButton btnNew;
        private DevExpress.XtraEditors.SplitContainerControl splitContainerControl1;

    }
}
